#!/bin/bash


# check if the user provided a filename as an agrument
if [ -v $1 ]; then
   echo "Error: No filename provided."
   exit 1
fi


filename=$1


as -o "${filename%.*}.o" "$filename"
ld -o a.out "${filename%.*}.o" csc35.o
./a.out
